import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import { Analytics } from "@vercel/analytics/next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased overflow-x-hidden`}
    >
      <body className="min-h-full flex flex-col overflow-x-hidden">
        <div className="flex-1 flex flex-col w-full overflow-x-hidden">
          {children}
        </div>
        
        {/* Adsterra Popunder Script */}
        <Script 
          src="https://pl29735767.effectivecpmnetwork.com/04/4f/b5/044fb5b14e5a5998ec2ef52f2ce0be7d.js"
          strategy="afterInteractive"
        />
        
        {/* Adsterra Social Bar Script */}
        <Script 
          src="https://pl29735765.effectivecpmnetwork.com/d6/c3/1c/d6c31c0bfd596d69aa44b4261b41e612.js"
          strategy="lazyOnload"
        />
        
        <Analytics />
      </body>
    </html>
  );
}

